export const WeeklyDatas = [
    {
        Num : '01',
        score : '264',
        person : 'John Doe',
        status : 'Student',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '02',
        score : '250',
        person : 'Jane Smith',
        status : 'Developer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '03',
        score : '236',
        person : 'Alex Johnson',
        status : 'Designer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '04',
        score : '222',
        person : 'Emily Brown ',
        status : 'Engineer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '05',
        score : '208',
        person : 'Micheal Lee',
        status : 'Data Scientist',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '06',
        score : '194',
        person : 'Daniel wilson',
        status : 'Marketing Specialist',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '07',
        score : '180',
        person : 'Ava white',
        status : 'Entrepreneur',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '08',
        score : '166',
        person : 'Olivia Rodriguez',
        status : 'Product Manager',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '09',
        score : '154',
        person : 'William Wilson',
        status : 'Software Engineer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '10',
        score : '134',
        person : 'Ethan Anderson',
        status : 'Content Creator',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '11',
        score : '86',
        person : 'Lucas Taylor',
        status : 'AI Researcher',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '12',
        score : '82',
        person : 'Isabella Scott',
        status : 'Project Manager',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '13',
        score : '64',
        person : 'Benjamin Adams',
        status : 'UX Researcher',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 01-08)',
    },
    {
        Num : '01',
        score : '264',
        person : 'John Doe',
        status : 'Student',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '02',
        score : '250',
        person : 'Jane Smith',
        status : 'Developer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '03',
        score : '236',
        person : 'Alex Johnson',
        status : 'Designer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '04',
        score : '222',
        person : 'Emily Brown ',
        status : 'Engineer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '05',
        score : '208',
        person : 'Micheal Lee',
        status : 'Data Scientist',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '06',
        score : '194',
        person : 'Daniel wilson',
        status : 'Marketing Specialist',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '07',
        score : '180',
        person : 'Ava white',
        status : 'Entrepreneur',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '08',
        score : '166',
        person : 'Olivia Rodriguez',
        status : 'Product Manager',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '09',
        score : '154',
        person : 'William Wilson',
        status : 'Software Engineer',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '10',
        score : '134',
        person : 'Ethan Anderson',
        status : 'Content Creator',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '11',
        score : '86',
        person : 'Lucas Taylor',
        status : 'AI Researcher',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '12',
        score : '82',
        person : 'Isabella Scott',
        status : 'Project Manager',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
    {
        Num : '13',
        score : '64',
        person : 'Benjamin Adams',
        status : 'UX Researcher',
        completed : '15 Completed',
        enrolled : '18 Enrolled',
        update : 'Last Updated on 17-07-2024',
        title : 'Weekly (Sep 09-15)',
    },
]