
export const CompleteData = [
    {
        Num : '01',
        Date : '28 Aug 2024',
        task : 'Coding',
        process : '05 Processes',
        perks : '35 Perks',
        title : 'Roadmap to be a UI/UX Designer',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '02',
        Date : '04 Sep 2024',
        task : 'Coding',
        process : '24 Processes',
        perks : '42 Perks',
        title : 'Learning essential design principles',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '03',
        Date : '11 Sep 2024',
        task : 'Coding',
        process : '12 Processes',
        perks : '27 Perks',
        title : 'Mastering design tools and software',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '04',
        Date : '18 Sep 2024',
        task : 'Coding',
        process : '13 Processes',
        perks : '38 Perks',
        title : 'Building strong portfolio',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '05',
        Date : '25 Sep 2024',
        task : 'Coding',
        process : '19 Processes',
        perks : '45 Perks',
        title : 'Developing  design process',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '06',
        Date : '2 Oct 2024',
        task : 'Coding',
        process : '08 Processes',
        perks : '31 Perks',
        title : 'Gaining Experience through internships',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '07',
        Date : '9 Oct 2024',
        task : 'Coding',
        process : '30 Processes',
        perks : '29 Perks',
        title : 'Networking with industry professionals',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '08',
        Date : '16 oct 2024',
        task : 'Coding',
        process : '25 Processes',
        perks : '37 Perks',
        title : 'Participating in design challenges',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '01',
        Date : '23 Oct 2024',
        task : 'Communication',
        process : '17 Processes',
        perks : '40 Perks',
        title : 'Exploring new design trends',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '10',
        Date : '30 Oct 2024',
        task : 'Coding',
        process : '22 Processes',
        perks : '33 Perks',
        title : 'Collaborating with cross-functional teams',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '1',
        Date : '06 Nov 2024',
        task : 'Design',
        process : '16 Processes',
        perks : '28 Perks',
        title : 'Attending design workshops',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '1',
        Date : '13 Nov 2024',
        task : 'Technical',
        process : '31 Processes',
        perks : '36 Perks',
        title : 'Creating interactive prototypes',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '1',
        Date : '20 Nov 2024',
        task : 'Collaboration',
        process : '26 Processes',
        perks : '39 Perks',
        title : 'Launching a personal design project',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '01',
        Date : '28 Aug 2024',
        task : 'Management',
        process : '05 Processes',
        perks : '35 Perks',
        title : 'Roadmap to be a UI/UX Designer',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '02',
        Date : '04 Sep 2024',
        task : 'Management',
        process : '24 Processes',
        perks : '42 Perks',
        title : 'Learning essential design principles',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '03',
        Date : '11 Sep 2024',
        task : 'Management',
        process : '12 Processes',
        perks : '27 Perks',
        title : 'Mastering design tools and software',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '04',
        Date : '18 Sep 2024',
        task : 'Management',
        process : '13 Processes',
        perks : '38 Perks',
        title : 'Building strong portfolio',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '05',
        Date : '25 Sep 2024',
        task : 'Management',
        process : '19 Processes',
        perks : '45 Perks',
        title : 'Developing  design process',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '06',
        Date : '2 Oct 2024',
        task : 'Management',
        process : '08 Processes',
        perks : '31 Perks',
        title : 'Gaining Experience through internships',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '07',
        Date : '9 Oct 2024',
        task : 'Management',
        process : '30 Processes',
        perks : '29 Perks',
        title : 'Networking with industry professionals',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '08',
        Date : '16 oct 2024',
        task : 'Management',
        process : '25 Processes',
        perks : '37 Perks',
        title : 'Participating in design challenges',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '09',
        Date : '23 Oct 2024',
        task : 'Management',
        process : '17 Processes',
        perks : '40 Perks',
        title : 'Exploring new design trends',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '10',
        Date : '30 Oct 2024',
        task : 'Management',
        process : '22 Processes',
        perks : '33 Perks',
        title : 'Collaborating with cross-functional teams',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '11',
        Date : '06 Nov 2024',
        task : 'Management',
        process : '16 Processes',
        perks : '28 Perks',
        title : 'Attending design workshops',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '12',
        Date : '13 Nov 2024',
        task : 'Management',
        process : '31 Processes',
        perks : '36 Perks',
        title : 'Creating interactive prototypes',
        update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '1',
        Date : '20 Nov 2024',
        task : 'Problem-solving',
        process : '26 Processes',
        perks : '39 Perks',
        title : 'Launching a personal design project',
        update : 'Last Updated on 17-07-2024',
    },
]


