
export const PracticewiseData = [
    {
        Num : '01',
        score : '264',
        person : 'John Doe',
        status : 'Student',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '02',
        score : '250',
        person : 'Jane Smith',
        status : 'Developer',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '03',
        score : '236',
        person : 'Alex Johnson',
        status : 'Designer',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '04',
        score : '222',
        person : 'Emily Brown ',
        status : 'Engineer',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '05',
        score : '208',
        person : 'Micheal Lee',
        status : 'Data Scientist',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '06',
        score : '194',
        person : 'Daniel wilson',
        status : 'Marketing Specialist',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '07',
        score : '180',
        person : 'Ava white',
        status : 'Entrepreneur',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '08',
        score : '166',
        person : 'Olivia Rodriguez',
        status : 'Product Manager',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '09',
        score : '154',
        person : 'William Wilson',
        status : 'Software Engineer',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '10',
        score : '134',
        person : 'Ethan Anderson',
        status : 'Content Creator',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '11',
        score : '86',
        person : 'Lucas Taylor',
        status : 'AI Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '12',
        score : '82',
        person : 'Isabella Scott',
        status : 'Project Manager',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '13',
        score : '64',
        person : 'Benjamin Adams',
        status : 'UX Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Roadmap to be a UIUX Designer',
    },
    {
        Num : '01',
        score : '86',
        person : 'Lucas Taylor',
        status : 'AI Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Lets chat about becoming a UIUX Designer!',
    },
    {
        Num : '01',
        score : '82',
        person : 'Isabella Scott',
        status : 'Project Manager',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Master prototyping tools',
    },
    {
        Num : '01',
        score : '64',
        person : 'Benjamin Adams',
        status : 'UX Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Understand user research methods',
    },
    {
        Num : '01',
        score : '86',
        person : 'Lucas Taylor',
        status : 'AI Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Practice visual design skills',
    },
    {
        Num : '01',
        score : '82',
        person : 'Isabella Scott',
        status : 'Project Manager',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Enhance interaction design knowledge',
    },
    {
        Num : '01',
        score : '64',
        person : 'Benjamin Adams',
        status : 'UX Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Collaborate with developers',
    },
    {
        Num : '02',
        score : '86',
        person : 'Lucas Taylor',
        status : 'AI Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Collaborate with developers',
    },
    {
        Num : '01',
        score : '82',
        person : 'Isabella Scott',
        status : 'Project Manager',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Stay updated on industry trends ',
    },
    {
        Num : '02',
        score : '64',
        person : 'Benjamin Adams',
        status : 'UX Researcher',
        date : '28 Aug 2024',
        update : 'Last Updated on 17-07-2024',
        title : 'Stay updated on industry trends ',
    },
]