export const Buttonlabels = [
    {
        label : 'Status'
    },
    {
        label : 'Update'
    },
    {
        label : 'Practice'
    },
    {
        label : 'Category'
    },
    {
        label : 'Sub Category'
    },
]
export const CompletedData = [
    {
        Num : '01',
        Date : '28 Aug 2024',
        task : 'Technical',
        perks : '35 Perks',
        Enroll : '215 Enrolled',
        Submit : '015 Submitted',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '02',
        Date : '15 Sep 2024',
        task : 'Management',
        perks : '25 Perks',
        Enroll : '162 Enrolled',
        Submit : '007 Submitted',
        title : 'Mastering the Art of Typography',
        Update : 'Last Updated on 18-07-2024',
    },
    {
        Num : '03',
        Date : '05 Oct 2024',
        task : 'Coding',
        perks : '40 Perks',
        Enroll : '198 Enrolled',
        Submit : '023 Submitted',
        title : 'Understanding User Behaviour',
        Update : 'Last Updated on 19-07-2024',
    },
    {
        Num : '04',
        Date : '25 Oct 2024',
        task : 'Innovation',
        perks : '30 Perks',
        Enroll : '177 Enrolled',
        Submit : '012 Submitted',
        title : 'Creating Interactive Designs',
        Update : 'Last Updated on 20-07-2024',
    },
    {
        Num : '05',
        Date : '12 Nov 2024',
        task : 'Problem-Solving',
        perks : '35 Perks',
        Enroll : '205 Enrolled',
        Submit : '030 Submitted',
        title : 'Ensuring Product Usability',
        Update : 'Last Updated on 21-07-2024',
    },
    {
        Num : '06',
        Date : '13 Nov 2024',
        task : 'Creativity',
        perks : '25 Perks',
        Enroll : '189 Enrolled',
        Submit : '008 Submitted',
        title : 'Improving User Experience',
        Update : 'Last Updated on 22-07-2024',
    },
]

export const AllSubmissionDetails = [
    {
        Num : '01',
        total : '11/15',
        Name : 'John Doe',
        Status : 'Student',
        Date : '28 Aug 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 17-07-2024',
    },
    {
        Num : '02',
        total : '14/15',
        Name : 'Jane Smith',
        Status : 'Fresher',
        Date : '04 Sep 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 18-07-2024',
    },
    {
        Num : '03',
        total : '03/15',
        Name : 'David Johnson',
        Status : 'Student',
        Date : '11 Sep 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 19-07-2024',
    },
    {
        Num : '04',
        total : '08/15',
        Name : 'Emily Brown',
        Status : 'Student',
        Date : '18 Sep 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 20-07-2024',
    },
    {
        Num : '05',
        total : '10/15',
        Name : 'Micheal Wilson',
        Status : 'Fresher',
        Date : '25 Sep 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 21-07-2024',
    },
    {
        Num : '06',
        total : '07/15',
        Name : 'Sarah Davis',
        Status : 'Student',
        Date : '02 Oct 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 22-07-2024',
    },
    {
        Num : '07',
        total : '12/15',
        Name : 'Robert Martinez',
        Status : 'Student',
        Date : '09 Oct 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 23-07-2024',
    },
    {
        Num : '08',
        total : '05/15',
        Name : 'Ava Wilson',
        Status : 'Fresher',
        Date : '16 Oct 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 24-07-2024',
    },
    {
        Num : '09',
        total : '13/15',
        Name : 'William Taylor',
        Status : 'Student',
        Date : '23 Oct 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 25-07-2024',
    },
    {
        Num : '10',
        total : '09/15',
        Name : 'Olivia Anderson',
        Status : 'Student',
        Date : '30 Oct 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 26-07-2024',
    },
    {
        Num : '11',
        total : '06/15',
        Name : 'James Garcia',
        Status : 'Fresher',
        Date : '06 Nov 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 27-07-2024',
    },
    {
        Num : '12',
        total : '11/15',
        Name : 'Sophia Clark',
        Status : 'Student',
        Date : '13 Nov 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 28-07-2024',
    },
    {
        Num : '13',
        total : '02/15',
        Name : 'Daniel Rodriguez',
        Status : 'Fresher',
        Date : '20 Nov 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 29-07-2024',
    },
    {
        Num : '14',
        total : '04/15',
        Name : 'Isabella Lewis',
        Status : 'Student',
        Date : '27 Nov 2024',
        title : 'Roadmap to be a UI/UX Designer',
        Update : 'Last Updated on 30-07-2024',
    },
]
